[mysqld]
port=3306
basedir="C:/Program Files/MySQL/MySQL Server 8.4"
datadir="d:/Lynn????/LynnHub/.mysql/data"
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default-storage-engine=INNODB
max_connections=200
bind-address=127.0.0.1
log-error="d:/Lynn????/LynnHub/.mysql/logs/error.log"

[client]
default-character-set=utf8mb4
port=3306

[mysql]
default-character-set=utf8mb4
